name: build

on:
  push:
  pull_request:

jobs:
  esp-idf:
    runs-on: ubuntu-latest
    container: espressif/idf:latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - esp32c6
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          . /opt/esp/idf/export.sh
          idf.py set-target "${{ matrix.target }}"
          idf.py build

